-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-01-17 20:45:59 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE SEQUENCE klucz_sztuczny_id_osoby START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE klucz_sztuczny_id_zakladu START WITH 1 INCREMENT BY 1 MAXVALUE 9999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE klucz_sztuczny_nr_tematu START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER podstaw_klucz_osoby 
    BEFORE INSERT ON Osoby 
    FOR EACH ROW 
    WHEN ( new.id_osoby is null ) 
declare
	wartosc_z_sekwencji NUMBER(5);
	czy_id_juz_bylo number(1);
begin
	loop
		select klucz_sztuczny_id_osoby.nextval into wartosc_z_sekwencji from dual;
		select count(*) into czy_id_juz_bylo from osoby where id_osoby = wartosc_z_sekwencji;
		exit when czy_id_juz_bylo = 0;
	end loop;
	:new.id_osoby := wartosc_z_sekwencji;
end; 
/

CREATE OR REPLACE TRIGGER podstaw_klucz_tematy 
    BEFORE INSERT ON Tematy 
    FOR EACH ROW 
    WHEN ( new.nr_tematu is null ) 
declare
	wartosc_z_sekwencji NUMBER(5);
	czy_id_juz_bylo number(1);
begin
	loop
		select klucz_sztuczny_nr_tematu.nextval into wartosc_z_sekwencji from dual;
		select count(*) into czy_id_juz_bylo from tematy where nr_tematu = wartosc_z_sekwencji;
		exit when czy_id_juz_bylo = 0;
	end loop;
	:new.nr_tematu := wartosc_z_sekwencji;
end; 
/

CREATE OR REPLACE TRIGGER podstaw_klucz_zaklady 
    BEFORE INSERT ON Zaklady 
    FOR EACH ROW 
    WHEN ( new.id_zakladu is null ) 
declare
	wartosc_z_sekwencji NUMBER(5);
	czy_id_juz_bylo number(1);
begin
	loop
		select klucz_sztuczny_id_zakladu.nextval into wartosc_z_sekwencji from dual;
		select count(*) into czy_id_juz_bylo from zaklady where id_zakladu = wartosc_z_sekwencji;
		exit when czy_id_juz_bylo = 0;
	end loop;
	:new.id_zakladu := wartosc_z_sekwencji;
end; 
/

CREATE OR REPLACE TRIGGER dodanie_pref_uprawnienia 
    BEFORE INSERT ON Preferencje 
    FOR EACH ROW 
DECLARE
	czy_osoba_jest_studentem varchar2(1 char);
BEGIN
	select czy_student into czy_osoba_jest_studentem from osoby where id_osoby = :new.id_studenta;
     if czy_osoba_jest_studentem = 'N' then
     	raise_application_error(-20225, 'Osoba nie bedaca studentem nie moze zlozyc preferencji');
	end if;
END; 
/

CREATE OR REPLACE TRIGGER dodanie_tematu_uprawnienia 
    BEFORE INSERT ON Tematy 
    FOR EACH ROW 
DECLARE
	czy_osoba_jest_pracownikiem varchar2(1 char);
BEGIN
	select czy_pracownik into czy_osoba_jest_pracownikiem from osoby where id_osoby = :new.id_opiekuna;
     if czy_osoba_jest_pracownikiem = 'N' then
     	raise_application_error(-20225, 'Osoba nie bedaca pracownikiem nie moze dodac tematu');
	end if;
END; 
/

CREATE OR REPLACE TRIGGER niezmienne_id_osoby 
    BEFORE UPDATE ON Osoby 
    FOR EACH ROW 
    WHEN ( new.id_osoby <> old.id_osoby ) 
BEGIN
    raise_application_error(-20225, 'Nie mozna zmieniac id osoby');
END; 
/

CREATE OR REPLACE TRIGGER niezmienne_id_zakladu 
    BEFORE UPDATE ON Zaklady 
    FOR EACH ROW 
    WHEN ( new.id_zakladu <> old.id_zakladu ) 
BEGIN
    raise_application_error(-20225, 'Nie mozna zmienic id_zakladu');
END; 
/

CREATE OR REPLACE TRIGGER niezmienny_nr_tematu 
    BEFORE UPDATE ON Tematy 
    FOR EACH ROW 
    WHEN ( new.nr_tematu <> old.nr_tematu ) 
BEGIN
    raise_application_error(-20225, 'Nie mozna zmienic numeru tematu');
END; 
/

CREATE OR REPLACE TRIGGER niezmienny_nr_albumu 
    BEFORE UPDATE ON Osoby 
    FOR EACH ROW 
    WHEN ( new.nr_albumu_studenta <> old.nr_albumu_studenta ) 
BEGIN
    raise_application_error(-20225, 'Nie mozna zmieniac numeru albumu studenta');
END; 
/

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             0
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           9
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
